PhoneGap 2.9.0rc1

diff --git a/lib/android/bin/templates/cordova/lib/start-emulator b/lib/android/bin/templates/cordova/lib/start-emulator
--- a/lib/android/bin/templates/cordova/lib/start-emulator
+++ b/lib/android/bin/templates/cordova/lib/start-emulator
@@ -16,8 +16,76 @@
 # specific language governing permissions and limitations
 # under the License.
 
-set -e
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+PROJECT_PATH=$( cd "$( dirname "$0" )/../.." && pwd )
 
-CORDOVA_LIB_PATH=$( cd "$( dirname "$0" )" && pwd )
+function dot {
+    sleep 1
+    echo -n "."
+}
 
-bash "$CORDOVA_LIB_PATH"/cordova start-emulator "$@"
+function wait_for_emulator {
+    local i="0"
+    echo -n "Waiting for emulator"
+    emulator_string=$($DIR/list-started-emulators)
+    while [ $? != 0 ]
+    do
+        dot
+        i=$[i+1]
+        emulator_string=$($DIR/list-started-emulators)
+    done
+    read -ra target <<< "$emulator_string"
+    echo ""
+    echo -n "Waiting for it to boot up (this can take a while)"
+    while [ $i -lt 300 ]
+    do
+        boot_anim=$(adb -s $target shell getprop init.svc.bootanim 2>&1)
+        if [[ "$boot_anim" =~ "stopped" ]] ; then
+            break
+        else
+            i=$[i+1]
+            dot
+        fi
+    done
+    # Device timeout: emulator has not started in time
+    if [ $i -eq 300 ]
+    then
+        echo ""
+        echo "Emulator timeout!"
+        exit 69
+    else
+        echo ""
+        echo "Connected!"
+    fi
+    # Unlock the device
+    adb -s $target shell input keyevent 82
+    exit 0
+}
+
+emulator_images=$("$DIR/list-emulator-images")
+if [ $? != 0 ]; then
+    echo "No emulators found, if you would like to create an emulator follow the instructions"
+    echo " provided here : http://developer.android.com/tools/devices/index.html"
+    echo " Or run 'android create avd --name <name> --target <targetID>' in on the command line."
+    exit 2
+fi
+
+# if target emulator is provided
+if [[ "$#" -eq 1 ]] ; then
+    # check that it exists
+    if [[ $emulator_images =~ $1 ]] ; then
+        #xterm -e emulator -avd $1 &
+        emulator -avd $1 1> /dev/null 2>&1 &
+    else
+        echo "Could not find the provided emulator '$1', make sure the emulator exists"
+        echo " by checking 'cordova/lib/list-emulator-images'"
+        exit 2
+    fi
+else
+    # start first emulator
+    read -ra emulator_list <<< "$emulator_images"
+    #xterm -e emulator -avd ${emulator_list[0]} &
+    emulator -avd ${emulator_list[0]} 1> /dev/null 2>&1 &
+fi
+
+wait_for_emulator
diff --git a/lib/android/example/cordova/run b/lib/android/example/cordova/run
--- a/lib/android/example/cordova/run
+++ b/lib/android/example/cordova/run
@@ -16,8 +16,66 @@
 # specific language governing permissions and limitations
 # under the License.
 
-set -e
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+PROJECT_PATH=$( cd "$DIR/.." && pwd )
 
-CORDOVA_PATH=$( cd "$( dirname "$0" )" && pwd )
+function run_on_device_or_emulator {
+    devices=`$DIR/lib/list-devices`
+    if [ $? = 0 ]; then
+        $DIR/lib/install-device
+    else
+        run_on_emulator
+    fi
+}
 
-bash "$CORDOVA_PATH"/lib/cordova run "$@"
+function run_on_emulator {
+    emulators=`$DIR/lib/list-started-emulators`
+    if [ $? = 0 ] ; then
+        $DIR/lib/install-emulator
+    else
+        images=`$DIR/lib/list-emulator-images`
+        if [ $? = 0 ] ; then
+            $DIR/lib/start-emulator
+            $DIR/lib/install-emulator
+        else
+            echo "No devices/emulators started nor images available to start. How are we supposed to do this, then?"
+            exit 2
+        fi
+    fi
+}
+
+
+
+if [[ "$#" -eq 2 ]] ; then
+    # TODO: the order of arguments here may be reversed from the assumption below
+    $DIR/build $2
+    if [[ $1 == "--device" ]] ; then
+        $DIR/lib/install-device
+    elif [[ $1 == "--emulator" ]] ; then
+        run_on_emulator
+    elif [[ $1 =~ "--target=" ]]; then
+        $DIR/lib/install-device $1
+    else
+        echo "Error : '$1' is not recognized as an install option"
+    fi
+elif [[ "$#" -eq 1 ]] ; then
+    if [[ $1 == "--debug" || $1 == "--release" || $1 == "--nobuild" ]] ; then
+        $DIR/build $1
+        run_on_device_or_emulator
+    elif [[ $1 == "--device" ]] ; then
+        $DIR/build
+        $DIR/lib/install-device
+    elif [[ $1 == "--emulator" ]] ; then
+        #$DIR/build
+        run_on_emulator
+    elif [[ $1 =~ "--target=" ]]; then
+        $DIR/build
+        $DIR/lib/install-device $1
+    else
+        echo "Error : '$1' is not recognized as an install option"
+    fi
+else
+    echo "Warning : [ --device | --emulate | --target=<targetID> ] not specified, using defaults."
+    $DIR/build
+    run_on_device_or_emulator
+fi
